#!/usr/bin/perl -w
use strict;

# $Id: gbrowse_popup,v 1.4 2007/12/06 22:16:38 smckay Exp $
# Sheldon McKay mckays@cshl.edu
# an AJAX handler for wormbase gbrowse popup balloons

use strict;
use lib '../lib';

use vars qw($DB $DBGFF $CLASS $NAME $SPECIES $OBJ);
use CGI qw(:standard);
use ElegansSubs ':DEFAULT';
use Ace::Browser::AceSubs ':DEFAULT';

$CLASS = param('class') || '';
$NAME  = param('name')  || '';
my $type  = param('type');

$DB    = OpenDatabase() || AceError("Couldn't open acedb database.");
if ($CLASS && $NAME) { 
  $OBJ   = $DB->fetch($CLASS => $NAME) || AceError("Couldn't find $CLASS $NAME in the database");
  $SPECIES = eval{$OBJ->Species}
}
$SPECIES ||= param('species');
$DBGFF = OpenGFFDB($DB,$SPECIES)   || AceError("Couldn't open GFF database.");

print header;

gene_description() if $type eq 'CG';
expression_pattern_description() if $type eq 'EXPR_PATTERN';

sub gene_description {
  my $default = $NAME;
  my $ace = $OBJ;
  my @tags = qw/
      Concise_description Detailed_description Provisional_description
      Sequence_features Molecular_function Biological_process
      Functional_pathway Functional_physical_interaction
      Expression Other_description Remarks/;
  my $desc;
  for my $tag (@tags) {
    $desc   = join(' ', eval{$ace->Corresponding_CDS->Gene->$tag});
    $desc ||= join(' ', eval{$ace->Gene->$tag});
    
    last if $desc;
  }
  unless ($desc) {
    my @desc = eval{$ace->Corresponding_CDS->DB_Remark};
    $desc = join('<br>',@desc);
  }
  $desc =~ s/^(.{512}).+/$1.../ if $desc;
  my $final = $desc ? "<b>$default:</b> $desc" : $default;
  print "<div style='padding:5px'>$final</div>";
}

sub expression_pattern_description {
  my $pattern = $DB->fetch(Expr_pattern => $NAME);
  my ($gene) = ElegansSubs::Bestname($pattern->Gene);
  my $type   = $pattern->Type;
  my $text   = $pattern->Pattern;
  $text      =~ s/;/,/g;
  $text      =~ s/,$//;
  my $cartoon = param('cartoon') ? "/db/gene/expression?name=$NAME;draw=1;thumb=300" : '';
  #undef $cartoon unless -e "/usr/local/wormbase/html/$cartoon";
  my $default = qq(<font color="steelblue"><b>$type for $gene</b></font><p><i>$text</i></p>);
  my @pics    = $pattern->Picture;
  my $url     = $pics[0] ? '/ace_images/elegans/external/'.$pics[0] : $cartoon;
  $url or print $default and exit;
  # image size constraints depending on type -- height must be specified
  #my $size;
  #$size = "width=300";#$pics[0] ? "width=300" : "width=220 height=65";
  print qq(<div style='padding:5px'>$default<p><img src="$url" width=300/></p></div>);
  exit;
}
