version: "3.7"
volumes:
  node_modules:
  yarn_cache:
services:
  local-proxy:
    image: nginx:1.13.7
    ports:
      - "${CATALYST_PORT}:80"
    volumes:
      - "./proxy/local-proxy/conf.d:/etc/nginx/conf.d"
      - "./logs/nginx:/var/log/nginx"
    environment:
      - WEBPACK_SERVER_PORT=${WEBPACK_SERVER_PORT}
    command: /bin/bash -c "envsubst '$$WEBPACK_SERVER_PORT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  website:
    image: wormbase/website-env:2.0.0-alpha.1
    command: >
      ./script/wormbase_server.pl -p 5000 -d -r --restart_directory ./lib
    volumes:
      - "./:/usr/local/wormbase/website-shared-files/html"
      - "./:/usr/local/wormbase/services"
      - "./:/usr/local/wormbase/databases"
      - "./:/usr/local/wormbase/website"
    environment:
      - WEBPACK_SERVER_PORT=${WEBPACK_SERVER_PORT}
    networks:
      - default
  webpack:
    image: node:latest
    ports:
      - "${WEBPACK_SERVER_PORT}:${WEBPACK_SERVER_PORT}"
    working_dir: /home/node/client
    command: >
      bash -c "yarn install --frozen-lockfile --verbose &&
      	       yarn run start"
    volumes:
      - type: bind
        source: ./
        target: /home/node/
        read_only: true
      - type: volume
        source: node_modules
        target: /home/node/client/node_modules
        volume:
          nocopy: true
      - type: volume
        source: yarn_cache
        target: /usr/local/share/.cache/yarn/v4
    environment:
      - PORT=${WEBPACK_SERVER_PORT}
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=wormbase
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=wormbase_user
    volumes:
      - "./util/sql/user_database.sql:/docker-entrypoint-initdb.d/user_database.sql"
