version: "3.7"
services:
  website:
    image: wormbase/website-env:1.0.2
    command: "./script/wormbase_server.pl -p 5000 -r -d"
    volumes:
      - "./:/usr/local/wormbase/website"
    environment:
      - WEBPACK_SERVER_PORT=${WEBPACK_SERVER_PORT}
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    networks:
      - default
      - wb-network
  webpack:
    image: node:12
    ports:
      - "${WEBPACK_SERVER_PORT}:${WEBPACK_SERVER_PORT}"
    working_dir: /home/node
    command: >
      bash -c "npm run start-client"
    volumes:
      - type: bind
        source: ./
        target: /home/node/
    environment:
      - PORT=${WEBPACK_SERVER_PORT}
networks:
  wb-network:
    external:
      name: wb-network
