# Wormbase WebSite Dockerfile

FROM ubuntu:18.10
MAINTAINER Adam Wright <adam.wright@wormbase.org>

#Install general packages
RUN \
  sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && \
  apt update && \
  apt -y upgrade && \
  apt install -y build-essential && \
  apt install -y software-properties-common && \
  apt install -y byobu curl git htop man unzip vim wget && \
  rm -rf /var/lib/apt/lists/*

## Install library prerequisites
RUN apt update; \
    apt -y install \
      zlib1g-dev \
      uuid \
      uuid-dev 

#install website dependencies
RUN apt -y install libmodule-install-perl \
    libmoose-perl \
    libtext-simpletable-perl \
    libplack-perl \
    libjson-perl

RUN mkdir -p /app

COPY . /app

RUN mkdir -p /app/extlib; \
    cd /app; \
    perl Makefile.PL; \
    make installdeps; 

# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /root

# Define default command.
CMD ["bash"]
