# Wormbase WebSite Dockerfile

FROM amd64/perl:5.26.3-threaded-stretch
MAINTAINER Sibyl Gao <sibyl@wormbase.org>

RUN cpanm --notest install Module::Install Catalyst::Devel Catalyst::Runtime;

WORKDIR /tmp
RUN apt-get update; \
    apt-get install -y --no-install-recommends \
	graphviz \
	# for DB_File::Lock
    	libdb-dev; \
    # needed for BLAT
    curl -O http://security.ubuntu.com/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1.1_amd64.deb; \
    apt-get install ./libpng12-0_1.2.54-1ubuntu1.1_amd64.deb; \
    curl -O -L https://github.com/libgd/libgd/releases/download/gd-2.2.5/libgd-2.2.5.tar.gz && tar zxvf libgd-2.2.5.tar.gz && cd libgd-2.2.5 && ./configure && make && make install; \
    # install first with --verbose to avoid timeout problem
    cpanm --notest --verbose install Memcached::libmemcached; \
    rm -rf /var/lib/apt/lists/*; \
    rm -rf /tmp/*



# RUN mkdir -p /app \
#     mkdir -p /tmp/wormbase; \
#     mkdir -p /usr/local/wormbase/tmp;

COPY ./Makefile.PL Makefile /app/
COPY ./lib /app/lib

WORKDIR /app
RUN mkdir -p /app/extlib; \
    perl Makefile.PL FIRST_MAKEFILE=MakefilePL.mk; \
    # use cpanm instead of cpan and skip tests
    cpanm --notest --force --installdeps .

WORKDIR /tmp
RUN curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"; \
    unzip awscli-bundle.zip; \
    ./awscli-bundle/install -b /usr/local/bin/aws; \
    rm -rf /tmp/*

# Set environment variables.
ENV HOME /root

# Define working directory.
RUN mkdir -p /usr/local/wormbase/website
WORKDIR /usr/local/wormbase/website

CMD ["/bin/bash"]